spring.application.name=backend

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://dpg-d8cka419rddc73dc3kj0-a.oregon-postgres.render.com:5432/lumiere_db_jsfk?sslmode=require
spring.datasource.username=lumiere_db_jsfk_user
spring.datasource.password=jWY8saOiamX8oVrZeY85JbyTE4sheAdH
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=2

server.error.include-message=always
server.error.include-stacktrace=always
